# Introduction

The pandas library has emerged into a power house of data manipulation tasks in python since it was developed in 2008. With its intuitive syntax and flexible data structure, it's easy to learn and enables faster data computation. The development of numpy and pandas libraries has extended python's multi-purpose nature to solve machine learning problems as well. The acceptance of python language in machine learning has been phenomenal since then.

In this tutorial, we'll learn about using numpy and pandas libraries for data manipulation from scratch. Instead of going into theory, we'll take a practical approach.

First, we'll understand the syntax and commonly used functions of the respective libraries. Later, we'll work on a real-life data set.

# Table of Contents

* Important things  about Numpy and Pandas
* Starting with Numpy
* Starting with Pandas

# Important things about Numpy and Pandas

1. The data manipulation capabilities of pandas are built on top of the numpy library. In a way, numpy is a dependency of the pandas library.

2. Pandas is best at handling tabular data sets comprising different variable types (integer, float, double, etc.). In addition, the pandas library can also be used to perform even the most naive of tasks such as loading data or doing feature engineering on time series data.

3. Numpy is most suitable for performing basic numerical computations such as mean, median, range, etc. Alongside, it also supports the creation of multi-dimensional arrays.

4. The best part of learning pandas and numpy is the strong active community support you'll get from around the world.

Just to give you a flavor of the numpy library, we'll quickly go through its syntax structures and some important commands such as slicing, indexing, concatenation, etc. All these commands will come in handy when using pandas as well. Let's get started!

# Starting with Numpy

Numpy is the most popular python library for matrix/vector computations. Due to python’s popularity, it is also one of the leading libraries for numerical analysis, and a frequent target for computing benchmarks and optimization.

Numpy is typically imported as np:

np is pretty much the standard acronym for the numpy and widely used in online documentation. Below we assume numpy has been imported as np.

In [1]:
import numpy as np

In [2]:
#load the library and check its version, just to make sure we aren't using an older version

np.__version__

'1.23.5'

## Creating Arrays
Numpy arrays are homogeneous in nature, i.e., they comprise one data type (integer, float, double, etc.) unlike lists.

Numpy is fundamentally based on arrays, N-dimensional data structures. Here we mainly stay with one- and two-dimensional structures (vectors and matrices) but the arrays can also have higher dimension (called tensors). 

Besides arrays, numpy also provides a plethora of functions that operate on the arrays, including vectorized mathematics and logical operations.

In [3]:
# vector of length 10

np.arange(10)  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 2x5 matrix

np.arange(10).reshape((2,5))  

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
#creating arrays with np.zeros

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#creating a 3 row x 8 column matrix with 

np.ones((3,8), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
#creating a matrix with a predefined value

np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [8]:
#create an array with a set sequence

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
#create an array of even space between the given range of values

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension

np.random.normal(0, 1, (3,3))

array([[ 2.16717288,  0.44632614, -0.94441676],
       [-0.67198732, -0.95856811,  0.85403003],
       [ 1.01032048, -0.7376396 ,  1.09790074]])

In [11]:
#create an identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
#set a random seed

np.random.seed(0)


x1 = np.random.randint(10, size=4) #one dimension
x2 = np.random.randint(10, size=(3,5)) #two dimension
x3 = np.random.randint(10, size=(3,5,5)) #three dimension


print("x1 ndim:", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim: 1
x1 shape: (4,)
x1 size:  4


In [13]:
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim: 2
x2 shape: (3, 5)
x2 size:  15


In [14]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (3, 5, 5)
x3 size:  75


## Array Indexing and Slicing

Indexing refer to extracting elements based on their position or certain criteria. This is one of the fundamental operations with arrays. 

There are two ways to extract elements: based on position, and based on logical criteria. Unfortunately, this also makes indexing somewhat confusing, and it needs some time to become familiar with.

The important thing to remember is that indexing in python starts at zero.

### Extracting elements based on position

In [15]:
# every second element

a = np.arange(12)
print(a[::2])  

[ 0  2  4  6  8 10]


In [16]:
# However, unlike lists, one can do vectorized assignments in numpy:
# assign multiple elements

a[5:11] = -1
a

array([ 0,  1,  2,  3,  4, -1, -1, -1, -1, -1, -1, 11])

In [17]:
# One can also extract multiple elements from a vector:
# extract 3 elements in one go

a[[4,5,7]]  

array([ 4, -1, -1])

In [18]:
# When working with matrices (2-D arrays), we need two indices, separated by comma. Comma separates two slices

c = np.arange(12).reshape((3,4))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
# 2nd row, 3rd column

c[1,2]  

6

In [20]:
# 2nd row

c[1] 

array([4, 5, 6, 7])

In [21]:
# Comma can separate not just two indices but two slices, so we can write
# all rows, 3rd column

c[:,2]  

array([ 2,  6, 10])

In [22]:
# 1st, 2nd row

c[:2]  

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
# 1s, 2nd row, first three columns

c[:2, :3]  

array([[0, 1, 2],
       [4, 5, 6]])

In [24]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [25]:
#assess value to index zero

x1[0]

4

In [26]:
#assess fifth value

x1[4]

8

In [27]:
#get the last value

x1[-1]

4

In [28]:
#get the second last value

x1[-2]

8

In [29]:
#in a multidimensional array, we need to specify row and column index

x2=np.array([[3, 7, 5, 5],[0, 1, 5, 9],[3, 0, 5, 0]])
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [30]:
#3rd row and last value from the 3rd column

x2[2,-1]

0

In [31]:
#replace value at 0,0 index

x2[0,0] = 12
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

In [32]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
#from start to 4th position

x[:5]

array([0, 1, 2, 3, 4])

In [34]:
#from 4th position to end

x[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
#from 4th to 6th position

x[4:7]

array([4, 5, 6])

In [36]:
#return elements at even place

x[ : : 2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
#return elements from first position step by two

x[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
#reverse the array

x[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

### Boolean indexing
An extremely widely used approach is to extract elements of an array based on a logical criteria. 

Fundamentally, it is just using a logical vector for indexing. 

The vector must be of the same lengts as the array in question, and the results contains only those elements the correspond to True in the indexing vector. 

Here is an example how we can do this manually:

In [39]:
a = np.array([1,2,7,8])

In [40]:
a > 5

array([False, False,  True,  True])

In [41]:
a[a > 5]

array([7, 8])

In [42]:
names = np.array(["Cyrus", "Darius", "Xerxes", "Artaxerxes", "Cyrus", "Darius"])
results = np.array([17, 14, 20, 18, 13, 15])

In [43]:
results[names == "Darius"]

array([14, 15])

In [44]:
names = np.array(["Cyrus", "Darius", "Xerxes"])
results = np.array([[17, 14], [20, 18], [13, 15]])

In [45]:
results[names == "Darius"]

array([[20, 18]])

In [46]:
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
scores = np.array([126, 115, 130, 141, 132])

In [47]:
# Extract all test scores that are smaller than 130

scores[scores < 130]

array([126, 115])

In [48]:
# Extract all test scores by Statira

scores[names == "Statira"]

array([115, 141])

In [49]:
# Add 10 points to Roxana’s scores. (You need to extract it first.)

scores[names == "Roxana"] = scores[names == "Roxana"] + 10  
scores

array([136, 115, 140, 141, 142])

### Array Concatenation

Many a time, we are required to combine different arrays. So, instead of typing each of their elements manually, you can use array concatenation to handle such tasks easily.

In [50]:
#You can concatenate two or more arrays at once.

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]

np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [51]:
#You can also use this function to create 2-dimensional arrays.

grid = np.array([[1,2,3],[4,5,6]])

np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
#Using its axis parameter, you can define row-wise or column-wise matrix

np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

what if you are required to combine a 2D array with 1D array? In such situations, we  can use `np.vstack` or `np.hstack` to do the task. Let's see how!

In [53]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])

np.vstack([x,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [54]:
#Similarly, you can add an array using np.hstack

z = np.array([[9],[9]])

np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

 we can split the arrays based on pre-defined positions. Let's see how!

In [55]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x1,x2,x3 = np.split(x,[3,6])

print(x1)
print(x2)
print(x3)

[0 1 2]
[3 4 5]
[6 7 8 9]


In [57]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
upper,lower = np.vsplit(grid,[2])
print (upper)
print (lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In addition, there are several other mathematical functions available in the numpy library such as sum, divide, multiple, abs, power, mod, sin, cos, tan, log, var, min, mean, max, etc. which you can be used to perform basic arithmetic calculations. Feel free to refer to numpy documentation for more information on such functions.

Let's move on to pandas now. Make sure you following each line below because it'll help you in doing data manipulation using pandas.

# Let's start with Pandas

Pandas relies heavily on numpy but is a separate package. Unfortunately, it also uses a somewhat different syntax and somewhat different defaults. However, as it is “made of” numpy, it works very well together with the latter.

Pandas contains two central data types: Series and DataFrame. Series is often used as a second-class citizen, just as a single variable (column) in data frame. But it can also be used as a vectorized dict that links keys (indices) to values. DataFrame is broadly similar to other dataframes as implemented in R or spark. When you extract its individual columns and rows you normally get those in the form of Series. So it is extremely useful to know the basics of Series when working with data frames. Both DataFrame and Series include index, a glorified row name, which is very useful for extracting information based on names, or for merging different variables into a data frame.

We start by introducing Series as this is a simpler data structure than DataFrame, and allows us to introduce index.

## Series
Series is a one-dimensional positional column (or row) of values. It is in some sense similar to list, but from another point of view it is more like a dict, as it contains index, and you can look up values based on index as a key. So it allows not only positional access but also index-based (key-based) access. In terms of internal structure, it is implemented with vectorized operations in mind, so it supports vectorized arithmetic, and vectorized logical, string, and other operations. Unlike dicts, it also supports multi-element extraction.

Let’s create a simple series:

In [59]:
#load library - pd is just an alias. 
import pandas as pd

In [60]:
s = pd.Series([1,2,5,6])
s

0    1
1    2
2    5
3    6
dtype: int64

Series is printed in two columns. The first one is the index, the second one is the value. In this example, index is essentially just the row number and it is not very useful. This is because we did not provide any specific index and hence pandas picked just the row number. Underneath the two columns, you can also see the data type, in this case it is 64-bit integer, the default data type for integers in python.

Now let’s make another example with a more informative index:

In [61]:
pop = pd.Series( [ 38, 26, 19, 19],
                 index = ['ca', 'tx', 'ny', 'fl'])

# population, in millions
pop

ca    38
tx    26
ny    19
fl    19
dtype: int64

Now the index is helpful: we are looking at state populations, and index tells us which state is in which row. Another advantage of possessing index is that even when we filter and manipulate the series, it’s index will still retain the original row label. So we know that index “fl” will always correspond to Florida. But if we have removed a few cases, or re-ordered the series, then Florida may not be on the fourth position any more.

In [62]:
# We can extract values and index using the corresponding attributes:

pop.values

array([38, 26, 19, 19], dtype=int64)

In [63]:
pop.index

Index(['ca', 'tx', 'ny', 'fl'], dtype='object')

In [64]:
# Note that values are returned as np array, and index is a special index object. 
# If desired, this can be converted to a list:

list(pop.index)

['ca', 'tx', 'ny', 'fl']

In [65]:
# Series also supports ordinary mathematics, e.g. we can do operations like

pop > 20

ca     True
tx     True
ny    False
fl    False
dtype: bool

In [66]:
# Create a series of 4 capital cities where the index is the name of corresponding country.

cities = pd.Series(["Brazzaville", "Libreville", "Malabo", "Yaoundé"],
                   index=["Congo", "Gabon", "Equatorial Guinea", "Cameroon"])
cities

Congo                Brazzaville
Gabon                 Libreville
Equatorial Guinea         Malabo
Cameroon                 Yaoundé
dtype: object

In [67]:
# 'Brazzaville'

cities.iloc[2]

'Malabo'

In [68]:
# 'Malabo'

cities.iloc[2]

'Malabo'

In [69]:
# Gabon    Libreville
# dtype: object

cities[["Gabon"]]

Gabon    Libreville
dtype: object

## DataFrame
DataFrame is the central data structure for holding 2-dimensional rectangular data. However, it also shares a number of features with Series, in particular the index, so you can imagine a data frame is just a number of series stacked next to each other. Also, extracting single rows or columns from DataFrames typically results in a series.

In [70]:
#create a data frame - dictionary is used here where keys get converted to column names and values to row values.

data = pd.DataFrame({'Country': ['India','Nepal','Pakistan','Bangladesh','Bhutan'],
                    'Rank':[11,40,100,130,101]})
data

Country  Rank
0       India    11
1       Nepal    40
2    Pakistan   100
3  Bangladesh   130
4      Bhutan   101

In [71]:
#We can do a quick analysis of any data set using:

data.describe()

Rank
count    5.000000
mean    76.400000
std     49.084621
min     11.000000
25%     40.000000
50%    100.000000
75%    101.000000
max    130.000000

To get the complete information about the data set, we can use`info()` function.

In [72]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [73]:
#Let's create another data frame.

data = pd.DataFrame({'group':['x', 'x', 'x', 'y','y', 'y', 'z', 'z','z'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     x     4.0
1     x     3.0
2     x    12.0
3     y     6.0
4     y     7.5
5     y     8.0
6     z     3.0
7     z     5.0
8     z     6.0

In [74]:
#Let's sort the data frame by ounces - inplace = True will make changes to the data

data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
1     x     3.0
6     z     3.0
0     x     4.0
7     z     5.0
3     y     6.0
8     z     6.0
4     y     7.5
5     y     8.0
2     x    12.0

We can sort the data by not just one column but multiple columns as well.

In [75]:
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     x    12.0
0     x     4.0
1     x     3.0
5     y     8.0
4     y     7.5
3     y     6.0
8     z     6.0
7     z     5.0
6     z     3.0

In [76]:
#create another data with duplicated rows

data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [77]:
#sort values 

data.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [78]:
#remove duplicates  

data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

we can also remove duplicates based on a particular column. Let's remove duplicate values from the k1 column.

In [79]:
data.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

Now, we will learn to categorize rows based on a predefined criteria. It happens a lot while data processing where you need to categorize a variable. 

In [80]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [81]:
meat_to_animal = {
    'bacon': 'poultry',
    'pulled pork': 'poultry',
    'pastrami': 'beef',
    'corned beef': 'beef',
    'honey ham': 'poultry',
    'nova lox': 'salmon',
    'duck': 'poultry',
    'lamb': 'poultry'
}

def meat_2_animal(series):
    if series['food'].lower() == 'bacon':
        return 'poultry'
    elif series['food'].lower() == 'pulled pork':
        return 'poultry'
    elif series['food'].lower() == 'pastrami':
        return 'beef'
    elif series['food'].lower() == 'corned beef':
        return 'beef'
    elif series['food'].lower() == 'honey ham':
        return 'poultry'
    elif series['food'].lower() == 'nova lox':
        return 'salmon'
    elif series['food'].lower() == 'duck':
        return 'poultry'
    elif series['food'].lower() == 'lamb':
        return 'poultry'
    else:
        return 'unknown'

data['animal'] = data.apply(meat_2_animal, axis='columns')


#create a new variable
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces   animal
0        bacon     4.0  poultry
1  pulled pork     3.0  poultry
2        bacon    12.0  poultry
3     Pastrami     6.0     beef
4  corned beef     7.5     beef
5        Bacon     8.0  poultry
6     pastrami     3.0     beef
7    honey ham     5.0  poultry
8     nova lox     6.0   salmon

In [82]:
#another way of doing it is: convert the food values to the lower case and apply the function

lower = lambda x: x.lower()
data['food'] = data['food'].apply(lower)
data['animal2'] = data.apply(meat_2_animal, axis='columns')
data

food  ounces   animal  animal2
0        bacon     4.0  poultry  poultry
1  pulled pork     3.0  poultry  poultry
2        bacon    12.0  poultry  poultry
3     pastrami     6.0     beef     beef
4  corned beef     7.5     beef     beef
5        bacon     8.0  poultry  poultry
6     pastrami     3.0     beef     beef
7    honey ham     5.0  poultry  poultry
8     nova lox     6.0   salmon   salmon

Another way to create a new variable is by using the assign function.

In [83]:
data.assign(new_variable = data['ounces']*10)

food  ounces   animal  animal2  new_variable
0        bacon     4.0  poultry  poultry          40.0
1  pulled pork     3.0  poultry  poultry          30.0
2        bacon    12.0  poultry  poultry         120.0
3     pastrami     6.0     beef     beef          60.0
4  corned beef     7.5     beef     beef          75.0
5        bacon     8.0  poultry  poultry          80.0
6     pastrami     3.0     beef     beef          30.0
7    honey ham     5.0  poultry  poultry          50.0
8     nova lox     6.0   salmon   salmon          60.0

Let's remove the column animal2 from our data frame.

In [84]:
data.drop('animal2',axis='columns',inplace=True)
data

food  ounces   animal
0        bacon     4.0  poultry
1  pulled pork     3.0  poultry
2        bacon    12.0  poultry
3     pastrami     6.0     beef
4  corned beef     7.5     beef
5        bacon     8.0  poultry
6     pastrami     3.0     beef
7    honey ham     5.0  poultry
8     nova lox     6.0   salmon

 A quick method for imputing missing values is by filling the missing value with any random number. Not just missing values, you may find lots of outliers in your data set, which might require replacing. 

In [85]:
#Series function from pandas are used to create arrays

data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [86]:
#replace -999 with NaN values

data.replace(-999, np.nan,inplace=True)
data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [87]:
#We can also replace multiple values at once.

data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace([-999,-1000],np.nan,inplace=True)
data

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

Now, let's learn how to rename column names and axis (row names).

In [88]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [89]:
#Using rename function

data.rename(index = {'Ohio':'SanF'}, columns={'one':'one_p','two':'two_p'},inplace=True)
data

one_p  two_p  three  four
SanF          0      1      2     3
Colorado      4      5      6     7
New York      8      9     10    11

In [90]:
#You can also use string functions

data.rename(index = str.upper, columns=str.title,inplace=True)
data

One_P  Two_P  Three  Four
SANF          0      1      2     3
COLORADO      4      5      6     7
NEW YORK      8      9     10    11

Let's learn about grouping data and creating pivots in pandas. It's an immensely important data analysis method which you'd probably have to use on every data set you work with.

In [91]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  1.509445 -0.038224
1    a  two  1.067775  0.367974
2    b  one -0.686589 -0.044724
3    b  two  0.014873 -0.302375
4    a  one -0.375666 -2.224404

In [92]:
#calculate the mean of data1 column by key1

grouped = df['data1'].groupby(df['key1'])
grouped.mean()

key1
a    0.733851
b   -0.335858
Name: data1, dtype: float64

let's see how to slice the data frame.

In [93]:
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-03 -0.491150  0.712678  1.113340 -2.153675
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057
2013-01-05 -1.050758  1.012079  1.543716 -0.402115
2013-01-06  0.864749 -0.226869  0.811160  0.287795

In [94]:
#get first 3 rows from the data frame

df[:3]

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-03 -0.491150  0.712678  1.113340 -2.153675

In [95]:
# slice based on date range

df['20130101':'20130104']

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-03 -0.491150  0.712678  1.113340 -2.153675
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057

In [96]:
#slicing based on column names

df.loc[:,['A','B']]

A         B
2013-01-01  0.724006  0.359003
2013-01-02  0.852926  0.018357
2013-01-03 -0.491150  0.712678
2013-01-04 -0.416111 -1.070897
2013-01-05 -1.050758  1.012079
2013-01-06  0.864749 -0.226869

In [97]:
#slicing based on both row index labels and column names

df.loc['20130102':'20130103',['A','B']]

A         B
2013-01-02  0.852926  0.018357
2013-01-03 -0.491150  0.712678

In [98]:
#slicing based on index of columns
#returns 4th row (index is 3rd)

df.iloc[3] 

A   -0.416111
B   -1.070897
C    0.221139
D   -1.123057
Name: 2013-01-04 00:00:00, dtype: float64

In [99]:
#returns a specific range of rows

df.iloc[2:4, 0:2]

A         B
2013-01-03 -0.491150  0.712678
2013-01-04 -0.416111 -1.070897

In [100]:
#returns specific rows and columns using lists containing columns or row indexes

df.iloc[[1,5],[0,2]] 

A         C
2013-01-02  0.852926  0.428304
2013-01-06  0.864749  0.811160

Similarly, we can do Boolean indexing based on column values as well. This helps in filtering a data set based on a pre-defined condition.

In [101]:
df[df.A > 0.5]

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-06  0.864749 -0.226869  0.811160  0.287795

In [102]:
#we can copy the data set

df2 = df.copy()
df2['E']=['one', 'one','two','three','four','three']
df2

A         B         C         D      E
2013-01-01  0.724006  0.359003  1.076121  0.192141    one
2013-01-02  0.852926  0.018357  0.428304  0.996278    one
2013-01-03 -0.491150  0.712678  1.113340 -2.153675    two
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057  three
2013-01-05 -1.050758  1.012079  1.543716 -0.402115   four
2013-01-06  0.864749 -0.226869  0.811160  0.287795  three

In [103]:
#select rows based on column values

df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2013-01-03 -0.491150  0.712678  1.113340 -2.153675   two
2013-01-05 -1.050758  1.012079  1.543716 -0.402115  four

In [104]:
#select all rows except those with two and four

df2[~df2['E'].isin(['two','four'])]

A         B         C         D      E
2013-01-01  0.724006  0.359003  1.076121  0.192141    one
2013-01-02  0.852926  0.018357  0.428304  0.996278    one
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057  three
2013-01-06  0.864749 -0.226869  0.811160  0.287795  three

We can also use a query method to select columns based on a criterion.

In [105]:
#list all columns where A is greater than C

df.query('A > C')

A         B         C         D
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-06  0.864749 -0.226869  0.811160  0.287795

In [106]:
#using OR condition

df.query('A < B | C > A')

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-03 -0.491150  0.712678  1.113340 -2.153675
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057
2013-01-05 -1.050758  1.012079  1.543716 -0.402115

Pivot tables are extremely useful in analyzing data using a customized tabular format.

In [107]:
#create a data frame

data = pd.DataFrame({'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [108]:
#calculate means of each group

data.pivot_table(values='ounces',index='group',aggfunc=np.mean)

ounces
group          
a      6.333333
b      7.166667
c      4.666667

In [109]:
#calculate count by each group

data.pivot_table(values='ounces',index='group',aggfunc='count')

ounces
group        
a           3
b           3
c           3