# Numpy

In [ ]:
# Bilimsel hesaplamalar için kullanılır.
# Arrayler/çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar
# Numpy dizileri python listelerine benzer fakat hız ve işlevsellik açısından python listelerinden daha kullanışlıdır.
# Çünkü listeler her bir eleman için ayrı ayrı bilgi tutarken numpy array'leri elemanlarını sabitlenmiş tipe zorlar 
# bu da veri saklama açısından büyük bir kolaylık sağlar

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

ab = []

for i in range(0,len(a)):
    ab.append(a[i] * b[i])
    
ab

[2, 6, 12, 20]

In [1]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])    

a * b                        # Bize daha az çabayla daha büüyük işeler yapmamızı sağlıyor

array([ 2,  6, 12, 20])

## NumPy Array'i Oluşturmak

In [ ]:
# Arrayleri oluşturmanın 3 farklı yolu vardır.
# 1) Liste ya da tuple benzeri nesneleri array'e döndürebiliriz.          np.array([1,2,3])
# 2) Built-in hazır fonksiyonlar yardımıyla arrayler oluşturabiliriz.     np.arange() , np.linspace() , np.logspace() vb.
# 3) Rastgele data üreterek                                               np.random modülünün içindeki fonksiyonlar ile.

In [10]:
import numpy as np    

In [11]:
np.array([1,2,3,4,5])      # numpy array'i tıpkı liste, tuple, sözlükler gibidir

array([1, 2, 3, 4, 5])

In [14]:
a = np.array([1,2,3,4,5])

In [15]:
type(a)

numpy.ndarray

In [16]:
np.array([3.14,4,2,13])    # array sabit tip tutuyor veri maliyetini düşürmek için o yüzden tüm içerik float oldu

array([ 3.14,  4.  ,  2.  , 13.  ])

In [17]:
np.array([3.14,4,2,13], dtype = "int")  # tüm içeriği integer yaptı

array([ 3,  4,  2, 13])

## Sıfırdan array oluşturma

In [18]:
np.zeros(10, dtype = int)    # tek boyutlu bir array-----vektör-----

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,5), dtype = int)    # çok boyutlu(2 boyutlu) bir array-----matris-----

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.full((3,5), 3)               # belirlediğimiz boyut bilgisiyle istediğimiz sayı üzeriden 

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [21]:
np.arange(0,31, 3)              # doğrusal bir dizi oluşturalım

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [13]:
np.arange(10,101,5)             # 10,15,20,25....100 şeklindeki arrayi oluşturunuz.

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [22]:
np.linspace(0,1,10)             # 2 değer arasında belirli sayıda array oluşturalım

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
np.linspace(30,50,6 , dtype=int)   # Endpoint bunda dahil.

array([30, 34, 38, 42, 46, 50])

In [12]:
np.logspace(1,3 , 5)       # 10**1 ile 10**3 arasında logaritmik artış yapan 5 tane veriden oluşan bir array oluştur.

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [14]:
np.random.rand(2,5)         # (2,5) formatında (0 - 1) aralığında array oluşturma

array([[0.88935676, 0.85223235, 0.23101219, 0.58003482, 0.07359282],
       [0.57466522, 0.3220031 , 0.57633736, 0.84242084, 0.30943184]])

In [23]:
np.random.normal(10,4, (3,4))     # ortalama 10 standart sapması 4 olam 3'e 4 matris oluşturma dağılımı biz belirttik
                                  # yani istediğimiz dağılım özellliğinde bir array oluşturmuş olduk

array([[10.07888684, 10.85178508, 10.84414677,  8.91203763],
       [13.46558114, 15.13963373, 16.96447709,  6.96282359],
       [ 9.6951544 ,  7.49746618, 13.72860005,  8.60192359]])

In [17]:
np.random.randint(15,50,5)        # rastgele int veri oluşturma

array([38, 41, 46, 33, 40])

In [24]:
np.random.randint(0,10, (3,3))      

array([[4, 5, 6],
       [7, 2, 4],
       [9, 6, 3]])

## NumPy Array Özellikleri

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [5]:
a = np.random.randint(10, size = 10)

In [6]:
a

array([4, 2, 7, 5, 3, 8, 7, 4, 1, 2])

In [7]:
a.ndim       # tek boyutlu array

1

In [9]:
a.shape          # 1 satır 10 sütun ama 1'i yazmıyor sütunu yazıyor o da tuple içinde olduğu için virgülle yazılıyor

(10,)

In [30]:
a.dtype

dtype('int32')

In [31]:
a.size

10

In [32]:
b = np.random.randint(10, size = (3,5))

In [33]:
b

array([[1, 1, 4, 7, 2],
       [6, 5, 5, 8, 5],
       [0, 7, 4, 1, 2]])

In [34]:
b.ndim       # 2 boyutlu array

2

In [35]:
b.shape     # boyut bilgisi

(3, 5)

In [36]:
b.size

15

In [37]:
b.dtype

dtype('int32')

## Yeniden Şekillendirme (reshaping)

In [2]:
np.arange(1,10)                    # vektör(tek boyutlu)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10).reshape((3,3))     # matrise(çok boyutlu) dönüştürme işlemi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a = np.arange(1,10)

In [5]:
a       # bu vektör 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = a.reshape((1,9))                # bir satır 9 sutun dan oluşan matris

In [8]:
b       # bu matris

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
b.ndim    # matris olduğunun kanıtı

2

## Array Birleştirme (Concatenation)

In [52]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [53]:
np.concatenate([x,y])           # tek boyut birleştirme

array([1, 2, 3, 4, 5, 6])

In [54]:
z = np.array([7,8,9])

In [55]:
np.concatenate([x,y,z])          # tek boyut birleştirme

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a = np.array([[1,2,3],            # 2 boyutlu array'i manuel oluşturduk
              [4,5,6]])           # a = np.array([[1,2,3], [4,5,6]])  yandakinle aynı ifade

In [58]:
np.concatenate([a,a])             # 2 boyutlu birleştirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# axis eksen belirtmek için kullanılır 
# axis = 0 satırları
# azis = 1 sütunları belirtir

In [59]:
np.concatenate([a,a], axis = 0 )      # satır bazında birleştirme (axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [60]:
np.concatenate([a,a], axis = 1 )       # sütun bazında birleştirme (axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma işlemleri (Splitting)

In [61]:
x = np.array([1,2,3,99,99,3,2,1])
np.split(x,[3,5,])                  # arrayi ilk 3'e, sonra 5'e kadar kalanida otamatik ayırıyor

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [63]:
a,b,c = np.split(x,[3,5,])          # ayırma işlemini değişkenlere atama

In [64]:
a

array([1, 2, 3])

In [65]:
b

array([99, 99])

In [66]:
c

array([3, 2, 1])

In [ ]:
# iki boyutlu ayırma

In [10]:
m = np.arange(16).reshape(4,4)   
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
np.vsplit(m, [2])              # satır bazında bölme 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [70]:
ust,alt = np.vsplit(m, [2])

In [71]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
np.hsplit(m, [2])               # sütun bazında bölme

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [75]:
sag,sol = np.hsplit(m, [2])

sag

In [77]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array sıralama (Sorting) 

In [78]:
v = np.array([2,1,4,3,5])

In [79]:
v

array([2, 1, 4, 3, 5])

In [80]:
np.sort(v)                 # NumPy dan özel fonksiyon çağrılınca verinin orjinal yapısı bozulmadı

array([1, 2, 3, 4, 5])

In [81]:
v

array([2, 1, 4, 3, 5])

In [82]:
v.sort()                    # direk sort() özel fonksiyon kullanımı verinin orjinal yapısını bozar 

In [83]:
v

array([1, 2, 3, 4, 5])

In [85]:
m = np.random.normal(20,5, (3,3))   # ortalama 20, standart sapması 5 olan 3'e 3 matris oluşturma

In [86]:
m

array([[29.919038  , 26.56728827, 19.7717729 ],
       [21.69566585, 18.55933605, 15.89158978],
       [10.58307723,  9.8069179 , 23.31018897]])

In [87]:
np.sort(m, axis = 1)                 # satırları sıralama

array([[19.7717729 , 26.56728827, 29.919038  ],
       [15.89158978, 18.55933605, 21.69566585],
       [ 9.8069179 , 10.58307723, 23.31018897]])

In [88]:
np.sort(m, axis = 0)                  # sütünları sıralama

array([[10.58307723,  9.8069179 , 15.89158978],
       [21.69566585, 18.55933605, 19.7717729 ],
       [29.919038  , 26.56728827, 23.31018897]])